### ISSUE TITLE
Take less horizontal space

### ISSUE THREAD

**Issue by tamoyal** [mindz-eye/MYTableViewIndex#17]
This is a bit of a nit pick but in my case it had serious implications. In order to tap outside of the section index to hit a table view row,  you have to tap pretty far to the left. You can compare this to the native Contacts app to see the difference.  For example, it interferes with the X in the screen shotted view. I tried to handle this through the `indexInset` property but that did not work.
![img_4799](https://user-images.githubusercontent.com/46859/33088301-47121ae6-cebb-11e7-8edd-033f66d04fac.PNG)

**Comment by tamoyal** [comment]
i was able to solve this by using the `TableViewIndex` component directly and doing the measurements myself

**Comment by mindz-eye** [comment]
It is possible to assign a closure to TableViewIndexController, which allows to layout TableViewIndex as you want. See `layouter` property for details.
