### ISSUE TITLE
Change color of truncation items.

### ISSUE THREAD

**Issue by pedrocruzlopez** [mindz-eye/MYTableViewIndex#25]
Hey!, I have a quick question, Is it possible to change the default color (which is blue) of the truncation item class?.

**Comment by mindz-eye** [comment]
Hi,
you can set `tintColor` for your TableViewIndex

**Comment by pedrocruzlopez** [comment]
> Hi,
> you can set `tintColor` for your TableViewIndex

Thanks very much
