### ISSUE TITLE
Add support for left TableViewIndex

### ISSUE THREAD

**Issue by imran20487** [mindz-eye/MYTableViewIndex#29]
The TableViewIndex is always displayed on the Right side of the tableView. 
Since I have Arabic text inside table view which has text from right to left it is so I need the TableViewIndex on the left side

**Comment by mindz-eye** [comment]
Not sure what you mean here. `TableViewIndexController` does support RTL out of the box:
![Simulator Screen Shot - iPhone Xs - 2019-06-23 at 11 34 14](https://user-images.githubusercontent.com/6574383/59980539-2ccc2280-95ac-11e9-8404-5c4ab6488b2f.png)
