### ISSUE TITLE
Interface Builder integration causes crash with "Unknown class MYTableViewIndex in Interface Builder file."

### ISSUE THREAD

**Issue by tjanela** [mindz-eye/MYTableViewIndex#5]
The offending line seems to be the @objc class name declaration (in TableViewIndex.swift):

@objc(MYTableViewIndex)

If this line is removed and the Class Name changed to TableViewIndex in Interface Builder everything works.

At tag 0.2.0

**Comment by mindz-eye** [comment]
I can't reproduce it in Xcode 8.3.2
Please re-check with 0.3.0
