### ISSUE TITLE
Support taptic engine? 

### ISSUE THREAD

**Issue by alexanderkhitev** [mindz-eye/MYTableViewIndex#6]
Hello! A plan to support taptic engine?

**Comment by mindz-eye** [comment]
Hi!
Right now I don't have an access to device supporting it. Will do as soon as I get it, probably within a month.

**Comment by alexanderkhitev** [comment]
Hello @mindz-eye! Thank you for response!

**Comment by mindz-eye** [comment]
Finally added in 0.4.0
